name := "Mean and Standard Deviation"

version := "0.0.0"

scalaVersion := "2.11.1"

libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.0" % "test"

libraryDependencies += "org.scala-lang.modules" %% "scala-async" % "0.9.1"

// SBT from the command line and IntelliJ IDEA project generated from this via the gen-idea target
// automatically find the transitive dependency on JUnit. The Eclipse project generated by the eclipse
// target appears to fail to do this.

scalacOptions += "-feature"
